### PR TITLE
From the end slicing for collections

### PR DESCRIPTION
**Pull request by nelson-wu**
This RFC proposes the addition of the `^` symbol in the current slicing syntax to index slices from the end of a collection.

### CODE REVIEW

**Comment by cartermp** [comment]
This will also have to make mention of how we handle `System.Index` and `System.Range` given that they're only in .NET Core 3.0 and we cannot take a simple dependency on them in FSharp.Core.

**Comment by nelson-wu** [comment]
Right now this RFC is slightly outdated in that it operates on the existing API signature for GetSlice, which through the 3D slicing PR we've found to be somewhat inadequate for our needs. If we choose to use Range/Index, we're definitely not using the existing API for GetSlice, which means the implementation of from-the-end slicing is going to be somewhat different from what is contained here.

**Comment by nelson-wu** [comment]
@dsyme @KevinRansom @cartermp Me and @TIHan came up with an updated design that removes the dependency on Length. Could you please look it over again?

**Comment by dsyme** [comment]
> @dsyme @KevinRansom @cartermp Me and @TIHan came up with an updated design that removes the dependency on Length. Could you please look it over again?

I like it!

**Comment by dsyme** [comment]
I will merge this, let's iterate from there

**Pull request merged**
