### PR TITLE
Update FS-1048-ce-builder-map.md

### PR DESCRIPTION
**Pull request by jwosty**
Add Unresolved Questions section

### CODE REVIEW

**Comment by jwosty** [comment]
Friendly ping @dsyme @cartermp to check the open pull requests in this repo

**Comment by jwosty** [comment]
@cartermp to which part are you referring?

**Comment by cartermp** [comment]
From `Map` to `MapReturn`. I suppose I mean _method_ change suggestion.

**Comment by jwosty** [comment]
@cartermp ah, gotcha.

**Pull request merged**
