### PR TITLE
Draft RFC for [<RequireNamedArgument>]

### PR DESCRIPTION
**Pull request by smoothdeveloper**
See
* suggestion: https://github.com/fsharp/fslang-suggestions/issues/414
* discussion: https://github.com/fsharp/fslang-design/discussions/538

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
Ready for review and merge to avoid someone taking my first RFC id 🙂

**Comment by Happypig375** [comment]
As if non-official RFCs get merged https://github.com/fsharp/fslang-design/pull/442

**Comment by smoothdeveloper** [comment]
@Happypig375 I'm not following what you mean, is there an extra step to get the document merged?

I'm reading on the readme.md that a PR should be submitted to "grab the token"

> Ideas which get "approved in principle" get an RFC entry based on the template, and a corresponding RFC discussion thread

But if it doesn't get merged to enact the "RFC entry", then #410 will be a reoccurring issue.

If the RFC draft (it is by no mean a final document since the discussion didn't take place) isn't merged, it is hard to have the discussion on it, etc.

Are you saying this shouldn't get merged? if so, should I add a warning about the RFC being "non-official" at the very top of the text?

If your concern holds, the readme.md needs clarification under "The Process".

**Comment by Happypig375** [comment]
I'm just saying that you can't really expect quick PR merging here.

**Comment by smoothdeveloper** [comment]
My inference is not as good as F# type checker, thanks for the additional context 🙂

**Pull request merged**
