### PR TITLE
[RFC FS-1144] Empty-bodied computation expressions

### PR DESCRIPTION
**Pull request by brianrourkeboll**
RFC for approved language suggestion https://github.com/fsharp/fslang-suggestions/issues/1232.

Discussion thread: https://github.com/fsharp/fslang-design/discussions/775
Proposed implementation: https://github.com/dotnet/fsharp/pull/17352

Click “Files changed” → “⋯” → “View file” for the rendered RFC.

### CODE REVIEW

**Comment by brianrourkeboll** [comment]
@T-Gro What's the protocol here now that the implementation PR has been merged? Should this be merged as well? And the language suggestion marked as resolved?

**Comment by T-Gro** [comment]
Yes, RFC merged && sorted into the appropriate language bucket.
Suggestion closed as done.

**Comment by brianrourkeboll** [comment]
@vzarytovskii When you have time, I believe this is also ready to merge.

**Comment by vzarytovskii** [comment]
Yep, looks good to me

**Pull request merged**
