### PR TITLE
Create FS-1102-pattern-matches-on-use-bindings.md

### PR DESCRIPTION
**Pull request by Happypig375**

### CODE REVIEW

**Review by cartermp — APPROVED** [review]
Thanks!

**Comment by charlesroddie** [comment]
This wasn't approved!

**Comment by dsyme** [comment]
@charlesroddie is correct, this hasn't been approved.

I thought I'd left a comment to this effect but I can't find it.  In short, what's approved is the use of a single underscore

    use _ = ...

The use of a pattern on the left is not approved.

**Comment by dsyme** [comment]
My longer comment here, thanks: https://github.com/fsharp/fslang-suggestions/issues/881#issuecomment-853807713

**Pull request merged**
