### PR TITLE
FS-1084: Allow using nameof as a constant in pattern matching

### PR DESCRIPTION
**Pull request by Tarmil**
[Rendered](https://github.com/Tarmil/fslang-design/blob/nameof-pattern/RFCs/FS-1084-nameof-pattern.md)

### CODE REVIEW

**Comment by Tarmil** [comment]
Oops, didn't realize [I stole @Happypig375's number though](https://github.com/fsharp/fslang-design/pull/442) :/ Maybe we should have a guideline to create PRs with a neutral number FS-XXXX and editable by maintainers, so that numbers are only assigned upon merge?

**Comment by cartermp** [comment]
I'm personally not in favor of having numbers in general 🙂 

That might be a good guideline though. @dsyme thoughts?

**Comment by Happypig375** [comment]
@Tarmil It's not the first time lol
#448
https://github.com/fsharp/fslang-design/commit/0168e65402b4a9c1b9404f0037196cfa4a2716c2

**Comment by dsyme** [comment]
> That might be a good guideline though. @dsyme thoughts?

Sure, though I think on merge we can double check too

**Pull request merged**
